name: MacOS compile
on: [workflow_call]
jobs:
  Macos-Compile:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Conan
        run: |
          pip install conan
          sudo ln -s ~/.local/bin/conan /usr/bin/conan
      - name: Create default profile
        run: conan profile new default --detect
      - name: build
        run: |
          mkdir build
          cd build && conan install .. --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True && cmake .. -G "Unix Makefiles"  && cmake --build . 
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build
