name: MacOS compile
on: [workflow_call]
jobs:
  Macos-Compile:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Create default profile
        run: conan profile new default --detect
      - name: pull EngineCoreSuper submodule
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: build
        run: |
          mkdir -p build
          cd build && conan install .. --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True && cmake .. -G "Unix Makefiles"  && cmake --build . 
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build