name: MacOS compile
on: [workflow_call]
jobs:
  Macos-Compile:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Create default profile
        run: conan profile new default --detect
      - name: build
        run: ./comp_linux.sh
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build
