name: test_linux_compile
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install deps
        run: sudo apt update && sudo apt install -y cmake && sudo apt-get install xorg-dev libudev-dev
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build
