name: Windows compile
on: [workflow_call]
jobs:
  Windows-Compile:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Create default profile
        run: conan profile new default --detect
      - name: build
        run: |
          mkdir build
          cd build && conan install .. --build=missing && cmake .. -G "Visual Studio 17"  -A x64 && cmake --build . --config RELEASE 
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build
