name: Linux compile
on: [workflow_call, push, delete]
jobs:
  Linux-Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install deps
        run: sudo apt update && sudo apt install -y cmake && sudo apt-get install xorg-dev libudev-dev
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Create default profile
        run: conan profile new default --detect
      - name: build
        run: |
          mkdir build
          cd build && conan install .. --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True && cmake .. -G "Unix Makefiles"  && cmake --build . 
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build
