name: MacOS compile
on: [workflow_call]
jobs:
  Macos-Compile:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Conan
        run: |
          brew install python
          sudo chown -R $(whoami) $(brew --prefix)/*
          sudo install -d -o $(whoami) -g admin /usr/local/Frameworks
          brew link python
          python3 --version
          brew update
          brew install conan
      - name: Create default profile
        run: conan profile new default --detect
      - name: build
        run: |
          mkdir build
          cd build && conan install .. --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True && cmake .. -G "Unix Makefiles"  && cmake --build . 
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/build
